<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Basic line</name>
   <tag></tag>
   <elementGuidId>e52eb3c0-f01f-4324-9a4d-aabbbd270554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;wrap&quot;)/div[2]/ul/li/ul/li/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;wrap&quot;)/div[2]/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/demo/line-basic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic line</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[2]/ul/li/ul/li/a</value>
   </webElementProperties>
</WebElementEntity>
